### ISSUE TITLE
Suggestion: Debounce hash updating

### ISSUE THREAD

**Issue by mdibaiee** [jboyer87/page-progress#1]
Hey, I like your idea, but it's slow, scrolling becomes laggy with this.

I'd suggest you use a [`debounce`](http://davidwalsh.name/javascript-debounce-function) (jQuery might already have that) function for updating the url `hash`. Right now, on every scroll event you're updating the url hash and I think that's what causes slowness.

**Comment by jboyer87** [comment]
Hey there, I agree with you that it's slow. I think that's a great idea and I'll work on implementing that soon. The version that is up is "quick-and-dirty" and it's one of my first creations. Thank you for the advice!

**Comment by jboyer87** [comment]
I have implemented a jQuery plugin called doTimeout (http://benalman.com/projects/jquery-dotimeout-plugin/) that achieves the same debouncing technique you referenced. The scroll function is now checking after a 250ms delay, which I believe greatly improves performance. The doTimeout also wraps the url hash function, so things should be faster across the board.

**Comment by mdibaiee** [comment]
Yes! It's working smoothly! :+1:

**Comment by jboyer87** [comment]
Thanks again! I credited you in the source.
